// Auto-generated by Wails at build time — see runtime.js for details.

export function EventsOn<T = any>(eventName: string, callback: (data: T) => void): () => void
export function EventsOff(eventName: string): void
export function WindowShow(): void
export function WindowHide(): void
