// This file is normally auto-generated by Wails. Checked in as a minimal
// placeholder — Wails overwrites it with the real runtime bridge the first
// time you run `wails dev` or `wails build`.

export function EventsOn(eventName, callback) {
  return window.runtime.EventsOn(eventName, callback)
}

export function EventsOff(eventName) {
  return window.runtime.EventsOff(eventName)
}

export function WindowShow() {
  return window.runtime.WindowShow()
}

export function WindowHide() {
  return window.runtime.WindowHide()
}
