// This file is normally auto-generated by Wails (`wails dev` / `wails build`)
// by inspecting the exported methods on the App struct in app.go. It's
// checked in here as a placeholder purely so `npm install && npm run dev`
// doesn't fail with a missing-module error before you've run Wails once.
// Once you run `wails dev`, Wails will overwrite this file with the real
// bindings — do not hand-edit it after that point.

export function GetConfig() {
  return window.go.main.App.GetConfig()
}

export function SaveConfig(cfg) {
  return window.go.main.App.SaveConfig(cfg)
}

export function GetPrinters() {
  return window.go.main.App.GetPrinters()
}

export function GetQueue() {
  return window.go.main.App.GetQueue()
}

export function RetryJob(jobId) {
  return window.go.main.App.RetryJob(jobId)
}

export function ConfirmJob(jobId) {
  return window.go.main.App.ConfirmJob(jobId)
}
