// Auto-generated by Wails at build time — see App.js for details.
import { AgentConfig } from '../../../src/components/Settings'
import { PrintJob } from '../../../src/components/Queue'

export function GetConfig(): Promise<AgentConfig>
export function SaveConfig(cfg: AgentConfig): Promise<void>
export function GetPrinters(): Promise<string[]>
export function GetQueue(): Promise<PrintJob[]>
export function RetryJob(jobId: string): Promise<void>
export function ConfirmJob(jobId: string): Promise<void>
